### ISSUE TITLE
Smaller servos are unclear

### ISSUE THREAD

**Issue by thomwolf** [AlexanderKoch-Koch/low_cost_robot#1]
Hi, thanks a lot for the amazing project.

Just a note that in the table you indicate conflicting references for the smaller motors:

---

3x Dynamixel xl330-w280
$72	https://www.robotis.us/dynamixel-xl330-m077-t/
https://emanual.robotis.com/docs/en/dxl/x/xl330-m288/

---

It's more a "M" than a "W" and probably more a m077 than a m288 I guess

**Comment by AlexanderKoch-Koch** [comment]
Thank you. I've fixed it now. It should be Dynamixel xl330-m288 with higher torque for the follower and Dynamixel xl330-w077 for the leader arm.
