### ISSUE TITLE
Any ideas on how to debug flakey dynamixel connections?

### ISSUE THREAD

**Issue by moaazsidat** [AlexanderKoch-Koch/low_cost_robot#14]
Having trouble consistently being able to connect to motors and scan them via dynamixel, wondering if there's ways to debug it more

* When attaching them one by one, it works _most_ of the times, and nothing shows up on scanning via Dynamixel wizard rest of the time
* When trying to connect one motor to another, nothing shows up on scanning via Dynamixel wizard 100% of the time
* When have the whole setup wired, the smaller motors are blinking red (seems like that's incorrect voltage error) – and nothing shows up on Dynamixel wizard scanning

**Comment by AlexanderKoch-Koch** [comment]
The Dynamixel wizard shows you the input voltage. You could check that this is correct. Otherwise, I have no idea.

**Comment by moaazsidat** [comment]
Gotcha, will debug more, thanks!
