### ISSUE TITLE
What is the load capacity of this robotic arm?

### ISSUE THREAD

**Issue by heroacool** [AlexanderKoch-Koch/low_cost_robot#9]
@AlexanderKoch-Koch Thank you for sharing; this is a great project. 
I'm curious about the maximum load capacity of this robotic arm, as it would help in assessing what kind of tasks the arm can perform.

**Comment by AlexanderKoch-Koch** [comment]
For the four-axis version, it's a few hundred grams. I've posted a video with a heavier object here: https://x.com/alexkoch_ai/status/1771649728129687789. The payload of the five-axis arm at full extension is close to zero.
